# publishDir = "docs"

baseURL = "https://qec-website.netlify.app/"
languageCode = "en"
title = "QEC Conference Website"
ignoreFiles = ["archetypes/.*"]

# Theme
theme = "devfest-theme-hugo"

# Params
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

# Google Analytics are currently disabled, 
# using it would officially require a cookie banner at least in the EU, and we don't have one...
# it's probably better not to track people anyways.
# GoogleAnalytics = "G-221GMGECQ6"

# [services]
#   [services.googleAnalytics]
#     id = "G-221GMGECQ6"

[params]
    title = "QEC Conference Website"
    date = "2025-09-15"
        currentYear = 2026
        description = "International Conference on Quantum Error Correction (QEC)"
        images = ["/images/social-share.jpg"]
        email = "admin@qec-conference.org"
        keywords = "event, quantum computation, quantum error correction, QEC"
        copyright = "We :heart: quantum"
        copyright_link = "https://github.com/qec-conference/qec-website"
        appleTouchIcon = "/apple-touch-icon.png"
        favicon32 = "/favicon-32x32.png"
        favicon16 = "/favicon-16x16.png"
        manifest = "/site.webmanifest"
        # safariPinnedTab = "/safari-pinned-tab.svg"
    
    [params.2026]
      city = "Santa Barbara, CA"
      timeanddate_cityid = 775 ## Placeholder ID, update as needed!
      themeColor = "#1e88e5"
      [params.2026.logos]
        jumbo = "/images/2026/background-2026.png"
        header = "/images/2026/logo-2026.png"
        banner = "/images/2026/banner-2026.jpg"    
    
    [params.logos]
        footer = "/images/logos/netlify-color-accent.svg"
        footer_link = "https://www.netlify.com"
    
    [server]
      [[server.redirects]]
          from = "/"
          to = "/2026/"
          status = 302
          force = true 


[languages]
[languages.en]
    weight = 1
    languageName = "us"

[taxonomies]
    tag = "tags"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        anonymizeIP = false
        disable = false
        respectDoNotTrack = false
        useSessionStorage = false
    [privacy.instagram]
        disable = true
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = true
        simple = false
    [privacy.youtube]
        disable = true
        privacyEnhanced = true






  [[menu.2026]]
    name = "Home"
    weight = 10
    identifier = "home"
    pageRef = '/2026'
  [[menu.2026]]
    name = "Technical Program"
    weight = 20
    identifier = "technical-program"
  [[menu.2026]]
    name = "Call for Submissions"
    weight = 21
    identifier = "call-for-papers"
    parent = "technical-program"
    pageRef = "/2026/call"
  [[menu.2026]]
    name = "Accepted Papers"
    weight = 22
    identifier = "accepted-papers"
    parent = "technical-program"
    pageRef = "/2026/accepted-papers"
  [[menu.2026]]
    name = "Attend"
    weight = 30
    identifier = "attend"
  [[menu.2026]]
    name = "Registration"
    weight = 31
    identifier = "registration"
    parent = "attend"
    pageRef = "/2026/registration"
  [[menu.2026]]
    name = "Code of Conduct"
    weight = 32
    identifier = "code-of-conduct"
    parent = "attend"
    pageRef = "/2026/code-of-conduct"
  [[menu.2026]]
    name = "Travel"
    weight = 33
    identifier = "travel"
    parent = "attend"
    pageRef = "/2026/travel"
  [[menu.2026]]
    name = "Sponsors"
    weight = 40
    identifier = "sponsors"
    pageRef = "/2026/partners"
  [[menu.2026]]
    name = "Committees"
    weight = 50
    identifier = "committees"
    pageRef = "/2026/team"
